name: Modbus_Simulation
channels:
  - defaults
dependencies:
  - bitarray=0.8.2=py36hfa6e2cd_0
  - certifi=2018.4.16=py36_0
  - pip=10.0.1=py36_0
  - python=3.6.5=h0c2934d_0
  - setuptools=39.1.0=py36_0
  - vc=14=h0510ff6_3
  - vs2015_runtime=14.0.25123=3
  - wheel=0.31.1=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - pip:
    - colored==1.3.93
    - dpkt==1.9.1
    - easygui==0.98.1
    - ptable==0.9.2
    - scapy-python3==0.23
prefix: C:\Users\ibaim\AppData\Local\conda\conda\envs\Modbus_Simulation

